name: Create Feature Branches from Tags

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create branch from"
        required: true
        type: string

jobs:
  create-feature-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get tag name
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "branch_name=features-based-on-$TAG" >> $GITHUB_OUTPUT

      - name: Check if branch already exists
        id: check_branch
        run: |
          BRANCH_NAME="${{ steps.get_tag.outputs.branch_name }}"
          if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH_NAME already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH_NAME does not exist"
          fi

      - name: Create feature branch
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          BRANCH_NAME="${{ steps.get_tag.outputs.branch_name }}"

          # Create branch from the tag
          git checkout -b "$BRANCH_NAME" "$TAG"
          git push origin "$BRANCH_NAME"

          echo "Created branch: $BRANCH_NAME from tag: $TAG"

      - name: Skip if branch exists
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          echo "Branch ${{ steps.get_tag.outputs.branch_name }} already exists. Skipping creation."
